### ISSUE TITLE
Problems with iOS 11.1

### ISSUE THREAD

**Issue by Nargly** [JohanDegraeve/iosxdripreader#20] opened 2017-11-06 03:37 UTC
Johan,

I'm seeing some pretty drastic issues with iOS 11.1 and iosxdripreader.  I can't blame your efforts, as this is not the only problem with iOS 11.1 I'm having.  Many apps have become unstable.  But for your record, here's what I'm dealing with:
Since installing 11.1 I can't seem to keep iosxdripreader working.  It crashes almost every time after I let the iPhone go to sleep.  When I open the app, it's dead and won't respond.  It will eventually go away, and need to be re-launched.  I'm trying a down grade to your version 1.1.7 to see if there is any affect there.

**Comment by JohanDegraeve** [comment] 2017-11-06 08:35
Hi,

I haven't upgraded yet to 11.1.
But I also experience recently crashes. I'm thinking the size of the app is maybe becoming just a little too big. Although I don't know exactly how iOS works, if it stores the complete file in memory or not.

What I notice several times is when I have other resource consuming apps running, then iosxdripreader crashes, for instance apps using GPS like tomtom or bikegpx.
Also whenever i attach it to my computer, it' almost always crashes and I need to restart it.

thanks for keeping us informed with your further test results

Johan

**Comment by Nargly** [comment] 2017-11-06 12:22
Johan,

I love testing, so no problems.  The downgrade to 1.1.7 was because that was the last version that was stable enough for me, but I couldn't get the transmitter re-paired with the app.  It did do the first step of pairing with the iPhone, but the app never picked it up.  I'll keep trying and down a little farther to 1.1.3 and let you know what the results are.

If that still doesn't work, I may try to downgrade the iPhone to iOS 10 to see what occurs.  I liked the changes in 11, but need this and other apps that are crashing to work.  (Yes, many more apps I use are having iOS 11 issues...)

**Comment by Nargly** [comment] 2017-11-08 03:02
Johan,

Done a bit of testing over the past day.  I installed 1.1.3 as you suggested and re-established good results.  I upgraded through versions and tested them for a couple hours each.  1.1.7 seems the most stable, but still has more issues under iOS 11.1 than before.  This version of iOS seems very problematic.  I hope Apple improves their offerings, and allows you and others more freedom to produce software soon.

**Comment by JohanDegraeve** [comment] 2017-11-08 07:17
@Nargly  you mean 1.1.3 is more stable ?

**Comment by Nargly** [comment] 2017-11-08 13:50
Actually, 1.1.7.  1.1.9 was also very stable.  1.1.3 disconnected more but was stable too.  After 1.1.9 I start seeing the problem with a couple readings, then the app crashes.  I didn't test long on most versions though, so there is room for error.
Also, due to the Azure issues earlier this week I destroyed my NightScout setup.  Still need to rebuild it so I can see what affect the versions are having on that.  Might be a week or two until I can get to that.

**Comment by christerjensen** [comment] 2017-11-09 10:48
Ive noticed the same with iosxdripreader 1.13 but we have ios 10.3.

It freezes at times, but also some crashes.

**Comment by JohanDegraeve** [comment] 2017-11-09 12:38
The only reason I can think off (since it's rather recently happening) is that the app is starting to take too much memory and iOS is closing the app due to memory constraints.

Either it is due to the new sounds (since 1.1.3) or there's some parts of the code taking too much memory. There seem to be changes also in iOS 11 related to memory management.

I'll do same tests, for instance with a build without the new sounds. Maybe also crash reports (should be visible in xCode) can give more info

**Comment by Nargly** [comment] 2017-11-09 12:40
Quick opinion, I like the original Dexcom app sounds.  Urgent but not too annoying.

**Comment by Nargly** [comment] 2017-11-09 12:45
I wonder if your dev tools allow the ability for "this" part stays memory resident and "this other" part can be off-loaded.  I'm a very novice .NET dev and know it has some abilities like that in libraries.  I've no clue on Apple stuff.

**Comment by JohanDegraeve** [comment] 2017-11-10 07:59
Actually when connection the iphone to xcode, i see a lot of crashes every day. (windows, devices, view device logs).

Anybody who can read those logs ?

**Comment by caiuscristian** [comment] 2017-11-10 09:29
I just had checked my device, running iOS 11.1 on an iPhone 7 Plus. For me xDrip runs very stable. However I also see a lot of crashes from different applications (once also from xDrip). All with the same reasons (screenshot attached):

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace <0xF>, Code 0x8badf00d
Triggered by Thread:  0

![screen shot 2017-11-10 at 10 22 51](https://user-images.githubusercontent.com/29673093/32651590-cda64392-c601-11e7-9918-1e8349aff36a.jpg)

It seems to be related to watchdog timeout and therefore terminated by the system. I found this on on the internet. Hope that helps:

https://developer.apple.com/library/content/technotes/tn2151/_index.html

**Quote:**
Killed [SIGKILL]

The process was terminated at the request of the system. Look at the Termination Reason field to better understand the cause of the termination.
....
Some crash reports may contain an un-named Exception Type, which will be printed as a hexadecimal value (e.g. 00000020). If you receive one of these crash reports, look directly to the Exception Codes field for more information.
...
The exception code 0x8badf00d indicates that an application has been terminated by iOS because a watchdog timeout occurred. The application took too long to launch, terminate, or respond to system events. One common cause of this is doing synchronous networking on the main thread. Whatever operation is on Thread 0 needs to be moved to a background thread, or processed differently, so that it does not block the main thread.
-----

Best
Cristian

**Comment by JohanDegraeve** [comment] 2017-11-10 11:56
Cristian,

are you using Dexcom shareupload ?

Could anyone else having this issue, and having xcode on mac, check since when crashes occur and check the app version (it's in the log as shown in the screenshot from Cristian) ?


Johan

**Comment by caiuscristian** [comment] 2017-11-10 13:59
No, I'm using the BluCon Nightrider.

Best
Cristian

**Comment by JohanDegraeve** [comment] 2017-11-10 21:49
networking is done on a seperate thread, not the main thread

**Comment by JohanDegraeve** [comment] 2017-11-11 10:36
I've seen for my uploads, that an upload was taking 10 seconds. I've now done a complete deletion of the mongodb contents (entries and devicestatus).
Now it's still 2 seconds, it still looks rather long, I remember when I started using this it was less than a second.

Don't know if this can have impact on those crashes, shouldn't be.

Anyone else experiencing crashes could you send me detailed tracing so I can check the upload time ?  (let me know in the mail if you experience crashes).

Or you can send the tracing to yourself and search for
"uploading_events_with_id"
and
"bgReadingToNSUploadSuccess"

timestamp is in the beginning of the line and shows the time difference

**Comment by Nargly** [comment] 2017-11-11 15:33
Just another side comment, iOS 11.1.1 just released improved stability on your 1.1.7 version.  Haven't tried newer version yet, but might this weekend if I get the time.

**Comment by christerjensen** [comment] 2017-11-12 15:51
Re-signed the app and installed on my own iPhone - the app has crashed once in 6 hours. The NS upload stopps at times, but not related to crash. iosxdrip 1.1.13 and iOS 11.1

Incident Identifier: 5CC452EF-B72A-4811-8758-E80BF47B3F10
CrashReporter Key:   5e0ed0520c043a249e82bf26f0424a5b53d1d6c9
Hardware Model:      iPhone8,4
Process:             iosxdripreader [55973]
Path:                /private/var/containers/Bundle/Application/ADBF6850-1F09-41A5-B935-2B4EC8DABBA1/iosxdripreader.app/iosxdripreader
Identifier:          net.johandegraeve.iosxdripreader
Version:             1.1.13 (1.1.13)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           net.johandegraeve.iosxdripreader [1517]


Date/Time:           2017-11-12 11:26:01.8326 +0100
Launch Time:         2017-11-12 11:13:13.2213 +0100
OS Version:          iPhone OS 11.1 (15B93)
Baseband Version:    6.17.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace <0xF>, Code 0x8badf00d
Triggered by Thread:  0

**Comment by christerjensen** [comment] 2017-11-12 15:55
The NS upload error is below - same error every 5 minutes until I turn on the screen. Address hidden...

2017-11-12 15:57:43.672 BackGroundFetchService.as : error = Error with domain = NSURLErrorDomain, code = -997, userinfo = (null), errordescription = Error Domain=NSURLErrorDomain Code=-997 "Lost connection to background transfer service" UserInfo={NSErrorFailingURLKey=https://xxx.azurewebsites.net/api/v1/entries, NSLocalizedDescription=Lost connection to background transfer service, NSErrorFailingURLStringKey=https://xxx.azurewebsites.net/api/v1/entries}
2017-11-12 15:57:43.675 DexcomShareService.as : in createAndLoadUrlRequestFailed but dexcomShareStatus is empty, not interested, returning
2017-11-12 15:57:43.678 NightScoutService.as : in nightScoutUploadFailed
2017-11-12 15:57:43.679 NightScoutService.as : upload_to_nightscout_unsuccessfullError with domain = NSURLErrorDomain, code = -997, userinfo = (null), errordescription = Error Domain=NSURLErrorDomain Code=-997 "Lost connection to background transfer service" UserInfo={NSErrorFailingURLKey=https://xxx.azurewebsites.net/api/v1/entries, NSLocalizedDescription=Lost connection to background transfer service, NSErrorFailingURLStringKey=https://xxx.azurewebsites.net/api/v1/entries}
2017-11-12 15:57:43.682 NightScoutService.as : syncfinished

**Comment by JohanDegraeve** [comment] 2017-11-12 16:26
NS upload error : I know this is the error always occurring. Since the beginning that it occurred. 
It seems to be a common known issue, when googling for "Lost connection to background transfer service"

**Comment by aheimli** [comment] 2017-11-12 19:24
I know nothing about the program, but tried Google. Found this (same error different case):

My error was that I used a dataTaskWithRequest instead of uploadtaskWithRequest or in your case downloadtaskWithRequest. Obviously a datatask can't run in the background and get's killed.

**Comment by christerjensen** [comment] 2017-11-12 19:25
I know nothing about the program, but tried Google. Found this (same error different case):

My error was that I used a dataTaskWithRequest instead of uploadtaskWithRequest or in your case downloadtaskWithRequest. Obviously a datatask can't run in the background and get's killed.

**Comment by christerjensen** [comment] 2017-11-12 19:27
Others point to the same sollution:

https://github.com/daltoniam/SwiftHTTP/issues/98

**Comment by JohanDegraeve** [comment] 2017-11-12 22:42
I'm using datataskwithrequest, but I tried uploadtaskwithrequest before

I just made a version using uploadtaskwithrequest, you can try : https://1drv.ms/u/s!AoD_n2ttq1dEnNZkYAvMmR9c31y01g
I'm also testing it.

here's the objective-c code
uploadtaskwithrequest
https://github.com/JohanDegraeve/ANE-BackgroundFetch/blob/uploadtaskwithrequest/ios/AirBackgroundFetch/BackgroundFetch.m#L104

and here the method is called
https://github.com/JohanDegraeve/ANE-BackgroundFetch/blob/uploadtaskwithrequest/ios/AirBackgroundFetch/AirBackgroundFetch.m#L191

**Comment by christerjensen** [comment] 2017-11-13 16:23
Hi Johan,
I downloaded and resigned it now - just installed it - will report back
tomorrow.

Regards
Christer

2017-11-12 23:42 GMT+01:00 Johan Degraeve <notifications@github.com>:

**Comment by christerjensen** [comment] 2017-11-13 18:00
The new NS upload also stops at times - but seems to resume. 

Error when upload is not working:
2017-11-13 18:52:40.433 [xdripreadertrace ANE-BackgroundFetch] uploadTaskWithRequest resumed nsurlsession
2017-11-13 18:52:40.435 BluetoothService.as : Disconnected from device or attempt to reconnect failed
2017-11-13 18:52:40.439 BluetoothService.as : it is a G5

Then a few minutes after it works - for some reason it is not 5 minutes after.
The app is suddenly in the foreground
2017-11-13 18:55:00.603 iosxdripreader.mxml : setting ModelLocator.isInForeground = true and dispatching event IosXdripReaderEvent.APP_IN_FOREGROUND

2017-11-13 18:55:00.734 [xdripreadertrace ANE-BackgroundFetch] uploadTaskWithRequest resumed nsurlsession
2017-11-13 18:55:00.851 [xdripreadertrace ANE-BackgroundFetch] ANESessionDelegate.m didReceive
2017-11-13 18:55:00.852 [xdripreadertrace ANE-BackgroundFetch] ANESessionDelegate.m session
2017-11-13 18:55:00.852 [xdripreadertrace ANE-BackgroundFetch] ANESessionDelegate.m there is a task
2017-11-13 18:55:00.858 [xdripreadertrace ANE-BackgroundFetch] ANESessionDelegate.m the task has a nsurlresponse
2017-11-13 18:55:00.861 [xdripreadertrace ANE-BackgroundFetch] ANESessionDelegate.m the nsurlresponse is a nshttpurlresponse
2017-11-13 18:55:00.864 [xdripreadertrace ANE-BackgroundFetch] ANESessionDelegate.m the status code is 200, dispatching result
2017-11-13 18:55:00.866 BackGroundFetchService.as : loadRequestSuccess, result only visible in NSLog : connect phone to Mac and use cfgutil
2017-11-13 18:55:00.870 NightScoutService.as : in bgReadingToNSUploadSuccess
2017-11-13 18:55:00.873 NightScoutService.as : upload_to_nightscout_successfull
2017-11-13 18:55:00.891 NightScoutService.as : in uploadcalibrations
2017-11-13 18:55:00.895 NightScoutService.as : syncfinished
2017-11-13 18:55:00.896 NightScoutService.as : setting syncRunning = false

**Comment by JohanDegraeve** [comment] 2017-11-13 18:25
I also  noticed today many drops but indeed it seems to come back. 

in the logs you need to look for "lost connection to background transfer service"
It does not come back in the foreground by itself.

where you see ModelLocator.isInForeground = true is where you've re-opened the app

iOS 11.1.1 seems much more stable, I didn't have crashes yet since a day

**Comment by christerjensen** [comment] 2017-11-13 18:40
Mine does resume automatically without using the phone. Tested a few times. There are many drops, but they resume within 15-20 minutes. I have no "lost connection to background transfer service" in my log.

**Comment by JohanDegraeve** [comment] 2017-11-14 22:53
I think it was better with the previous version, ie with dataTaskWithRequest

**Comment by JohanDegraeve** [comment] 2017-11-27 08:44
NS upload has become very stable in the lastest release. In fact I didn't have any failure since 1.1.15

**Comment by miguelkennedy** [comment] 2017-11-27 09:45
;)

**Comment by JohanDegraeve** [comment] 2017-11-27 09:55
yes thanks to @miguelkennedy :) He doesn't like to admit it but it is

**Comment by miguelkennedy** [comment] 2017-11-27 11:10
We're a team... no need to take individual credit for every bug I correct or new feature I code... Credit goes to the entire team... This app is made only for the greater good of the diabetic community, that's the only thing that matters. Every milestone we achieve in the app is due to the work of every developer involved... we're stronger together ;)

**Comment by Nargly** [comment] 2017-11-29 14:00
Johan,

Just wanted to post that since iOS 11.1.2 and iosxdripreader 1.1.16 I've had the most solid results to date.  2 days and zero drops or stops.  Well, until this morning when Azure needed a quick reset, but that's not fixable :)  Anyway, great job!

**Comment by JohanDegraeve** [comment] 2017-11-29 14:08
Hi,

yes since 1.1.16 NS upload is error free, also for me.

BT I may have had one problem but I'm not sure if it was app related, may have been that iphone was too far away,

Johan

**Comment by JohanDegraeve** [comment] 2017-12-05 21:32
closing this one as there's no more issues repoted since 1.1.17

**Closed by JohanDegraeve** 2017-12-05 21:32 UTC

**Comment by alcscg** [comment] 2018-07-20 13:08
950]
Path:                /private/var/containers/Bundle/Application/16152534-EEF8-4B3B-BB6C-B5A61AF05EB1/Kodi.app/Kodi
Identifier:          com.tweakbox.kodi
Version:             1.0
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.tweakbox.kodi [700]


Date/Time:           2018-07-03 22:37:55.9548 -0500
Launch Time:         2018-07-03 22:37:00.2155 -0500
OS Version:          iPhone OS 11.2.6 (15D100)
Baseband Version:    1.62.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000001804fcb40
VM Region Info: 0x1804fcb40 is not in any region.  Bytes after previous region: 252300097  Bytes before following region: 83653824
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                  00000001713d8000-0000000171460000 [  544K] rw-/rwx SM=COW  thread 39
--->  GAP OF 0x14064000 BYTES
      unused shlib __TEXT    00000001854c4000-00000001854ee000 [  168K] r-x/r-x SM=COW  ... this process

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libobjc.A.dylib               	0x0000000185588430 0x18556c000 + 115760
1   CoreFoundation                	0x00000001862bd13c 0x1861e8000 + 872764
2   CoreFoundation                	0x00000001862bc6dc 0x1861e8000 + 870108
3   CoreFoundation                	0x00000001862bc440 0x1861e8000 + 869440
4   CoreFoundation                	0x0000000186339e24 0x1861e8000 + 1383972
5   CoreFoundation                	0x00000001861f2d60 0x1861e8000 + 44384
6   Foundation                    	0x0000000186c1f348 0x186c19000 + 25416
7   Celestial                     	0x000000018b82d0a8 0x18b822000 + 45224
8   Celestial                     	0x000000018b82d004 0x18b822000 + 45060
9   CoreFoundation                	0x00000001862bd13c 0x1861e8000
